name: crypto_calculator
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  intl: ^0.17.0
  retrofit: ^3.0.1+1
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  retrofit_generator: ^4.0.3+1


flutter:

  uses-material-design: true

  assets:
    - images/

